version: '3.4'

networks:
  roadeye_service-network:
    driver: bridge 

services:
  roadeye_service:
    image: omarmaysour/roadeye_service:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"     
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=roadeye;username=postgres;password=postgres"
    networks:
      - roadeye_service-network  
  
  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "roadeye"
    networks:
      - roadeye_service-network
volumes:
  db_volume: